@echo off
echo Starting HealthFirst application...

echo Starting backend server...
start cmd /k "cd backend && call run_server.bat"

echo Starting frontend server...
start cmd /k "cd frontend && call run_dev.bat"

echo HealthFirst application is starting...
echo Please wait while the servers initialize... 