services:
  - type: web
    name: healthwise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONPATH
        value: .
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://healthwise-afya-siri.vercel.app
      - key: CHROMA_PERSIST_DIRECTORY
        value: /data
      - key: UPLOAD_FOLDER
        value: /uploads

    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
      
    disk:
      name: uploads-disk
      mountPath: /uploads
      sizeGB: 1 